/* cds-fields.js - Common Data Set field dictionary for the market page's
   Common Data Set tab (market.js renderCdsTab). One entry per dbo.cds_facts
   field: [field, label]. Order here = display order within each CDS section.
   Fields that appear in the data but not here are appended to their section
   with a humanised label, so a new extraction field never disappears.
   Generated from the field list on 2026-09-17; edit labels freely. */
window.CDS_SECTIONS = [
  { item: "B1", title: "Enrollment by Level, Status and Gender" },
  { item: "B2", title: "Race, Ethnicity and Nonresident Enrollment" },
  { item: "B22", title: "First-Year Retention" },
  { item: "B4-B21", title: "Graduation Rates" },
  { item: "C1", title: "First-Year Admissions Funnel" },
  { item: "C12", title: "High School GPA" },
  { item: "D2", title: "Transfer Admissions" },
  { item: "F1", title: "Student Life: Housing, Residency, Greek Life and Age" },
  { item: "G1", title: "Tuition, Fees and Room and Board" },
  { item: "H2", title: "Need-Based Financial Aid" },
  { item: "H5", title: "Student Debt at Graduation" },
  { item: "J1", title: "Bachelor's Degrees Conferred by Field" },
];

window.CDS_FIELDS = [
  /* B1 */
  ["ENR_GRAND_TOTAL", "Total enrollment (all levels)"],
  ["ENR_UG_TOTAL", "Undergraduate enrollment"],
  ["ENR_GR_TOTAL", "Graduate enrollment"],
  ["ENR_UG_FT_MALE", "Undergraduate full-time: men"],
  ["ENR_UG_FT_FEMALE", "Undergraduate full-time: women"],
  ["ENR_UG_FT_ANOTHER", "Undergraduate full-time: another gender"],
  ["ENR_UG_FT_UNKNOWN", "Undergraduate full-time: gender unknown"],
  ["ENR_UG_FT_FIRSTTIME_MALE", "Undergraduate full-time, first-time: men"],
  ["ENR_UG_FT_FIRSTTIME_FEMALE", "Undergraduate full-time, first-time: women"],
  ["ENR_UG_FT_FIRSTTIME_ANOTHER", "Undergraduate full-time, first-time: another gender"],
  ["ENR_UG_FT_FIRSTTIME_UNKNOWN", "Undergraduate full-time, first-time: gender unknown"],
  ["ENR_UG_PT_MALE", "Undergraduate part-time: men"],
  ["ENR_UG_PT_FEMALE", "Undergraduate part-time: women"],
  ["ENR_UG_PT_ANOTHER", "Undergraduate part-time: another gender"],
  ["ENR_UG_PT_UNKNOWN", "Undergraduate part-time: gender unknown"],
  ["ENR_UG_PT_FIRSTTIME_MALE", "Undergraduate part-time, first-time: men"],
  ["ENR_UG_PT_FIRSTTIME_FEMALE", "Undergraduate part-time, first-time: women"],
  ["ENR_UG_PT_FIRSTTIME_ANOTHER", "Undergraduate part-time, first-time: another gender"],
  ["ENR_UG_PT_FIRSTTIME_UNKNOWN", "Undergraduate part-time, first-time: gender unknown"],
  ["ENR_GR_FT_MALE", "Graduate full-time: men"],
  ["ENR_GR_FT_FEMALE", "Graduate full-time: women"],
  ["ENR_GR_FT_ANOTHER", "Graduate full-time: another gender"],
  ["ENR_GR_FT_UNKNOWN", "Graduate full-time: gender unknown"],
  ["ENR_GR_FT_FIRSTTIME_MALE", "Graduate full-time, first-time: men"],
  ["ENR_GR_FT_FIRSTTIME_FEMALE", "Graduate full-time, first-time: women"],
  ["ENR_GR_FT_FIRSTTIME_ANOTHER", "Graduate full-time, first-time: another gender"],
  ["ENR_GR_FT_FIRSTTIME_UNKNOWN", "Graduate full-time, first-time: gender unknown"],
  ["ENR_GR_PT_MALE", "Graduate part-time: men"],
  ["ENR_GR_PT_FEMALE", "Graduate part-time: women"],
  ["ENR_GR_PT_ANOTHER", "Graduate part-time: another gender"],
  ["ENR_GR_PT_UNKNOWN", "Graduate part-time: gender unknown"],
  ["ENR_GR_PT_FIRSTTIME_MALE", "Graduate part-time, first-time: men"],
  ["ENR_GR_PT_FIRSTTIME_FEMALE", "Graduate part-time, first-time: women"],
  ["ENR_GR_PT_FIRSTTIME_ANOTHER", "Graduate part-time, first-time: another gender"],
  ["ENR_GR_PT_FIRSTTIME_UNKNOWN", "Graduate part-time, first-time: gender unknown"],
  /* B2 */
  ["RACE_WHITE_FTFY", "White: first-time first-year"],
  ["RACE_WHITE_UG_DEGREE", "White: degree-seeking undergrads"],
  ["RACE_WHITE_UG_TOTAL", "White: all undergrads"],
  ["RACE_BLACK_FTFY", "Black / African American: first-time first-year"],
  ["RACE_BLACK_UG_DEGREE", "Black / African American: degree-seeking undergrads"],
  ["RACE_BLACK_UG_TOTAL", "Black / African American: all undergrads"],
  ["RACE_HISPANIC_FTFY", "Hispanic / Latino: first-time first-year"],
  ["RACE_HISPANIC_UG_DEGREE", "Hispanic / Latino: degree-seeking undergrads"],
  ["RACE_HISPANIC_UG_TOTAL", "Hispanic / Latino: all undergrads"],
  ["RACE_ASIAN_FTFY", "Asian: first-time first-year"],
  ["RACE_ASIAN_UG_DEGREE", "Asian: degree-seeking undergrads"],
  ["RACE_ASIAN_UG_TOTAL", "Asian: all undergrads"],
  ["RACE_AMERICAN_INDIAN_FTFY", "American Indian / Alaska Native: first-time first-year"],
  ["RACE_AMERICAN_INDIAN_UG_DEGREE", "American Indian / Alaska Native: degree-seeking undergrads"],
  ["RACE_AMERICAN_INDIAN_UG_TOTAL", "American Indian / Alaska Native: all undergrads"],
  ["RACE_PACIFIC_ISLANDER_FTFY", "Native Hawaiian / Pacific Islander: first-time first-year"],
  ["RACE_PACIFIC_ISLANDER_UG_DEGREE", "Native Hawaiian / Pacific Islander: degree-seeking undergrads"],
  ["RACE_PACIFIC_ISLANDER_UG_TOTAL", "Native Hawaiian / Pacific Islander: all undergrads"],
  ["RACE_TWO_OR_MORE_FTFY", "Two or more races: first-time first-year"],
  ["RACE_TWO_OR_MORE_UG_DEGREE", "Two or more races: degree-seeking undergrads"],
  ["RACE_TWO_OR_MORE_UG_TOTAL", "Two or more races: all undergrads"],
  ["RACE_NONRESIDENT_FTFY", "Nonresident (international): first-time first-year"],
  ["RACE_NONRESIDENT_UG_DEGREE", "Nonresident (international): degree-seeking undergrads"],
  ["RACE_NONRESIDENT_UG_TOTAL", "Nonresident (international): all undergrads"],
  ["RACE_UNKNOWN_FTFY", "Race / ethnicity unknown: first-time first-year"],
  ["RACE_UNKNOWN_UG_DEGREE", "Race / ethnicity unknown: degree-seeking undergrads"],
  ["RACE_UNKNOWN_UG_TOTAL", "Race / ethnicity unknown: all undergrads"],
  ["RACE_TOTAL_FTFY", "Total: first-time first-year"],
  ["RACE_TOTAL_UG_DEGREE", "Total: degree-seeking undergrads"],
  ["RACE_TOTAL_UG_TOTAL", "Total: all undergrads"],
  ["ENR_NONRESIDENT_FTFY", "Nonresident (international) headcount: first-time first-year"],
  ["ENR_NONRESIDENT_UG_DEGREE", "Nonresident (international) headcount: degree-seeking undergrads"],
  ["ENR_NONRESIDENT_UG_TOTAL", "Nonresident (international) headcount: all undergrads"],
  /* B22 */
  ["RET_FRESHMAN_PCT", "First-year retention rate"],
  ["RET_COHORT_N", "Retention cohort (first-time full-time)"],
  ["RET_STILL_ENROLLED_N", "Still enrolled the following fall"],
  /* B4-B21 */
  ["GRAD_COHORT_N", "Graduation cohort size"],
  ["GRAD_4YR_N", "Graduated within 4 years"],
  ["GRAD_4YR_PCT", "4-year graduation rate"],
  ["GRAD_6YR_N", "Graduated within 6 years"],
  ["GRAD_6YR_PCT", "6-year graduation rate"],
  /* C1 */
  ["ADM_FY_APPLIED_TOTAL", "Applied: total"],
  ["ADM_FY_APPLIED_MALE", "Applied: men"],
  ["ADM_FY_APPLIED_FEMALE", "Applied: women"],
  ["ADM_FY_APPLIED_ANOTHER", "Applied: another gender"],
  ["ADM_FY_APPLIED_UNKNOWN", "Applied: gender unknown"],
  ["ADM_FY_APPLIED_INSTATE", "Applied: in-state"],
  ["ADM_FY_APPLIED_OUTSTATE", "Applied: out-of-state"],
  ["ADM_FY_APPLIED_INTL", "Applied: international"],
  ["ADM_FY_APPLIED_RESIDENCY_UNKNOWN", "Applied: residency unknown"],
  ["ADM_FY_APPLIED_RESIDENCY_TOTAL", "Applied: residency total"],
  ["ADM_FY_ADMITTED_TOTAL", "Admitted: total"],
  ["ADM_FY_ADMITTED_MALE", "Admitted: men"],
  ["ADM_FY_ADMITTED_FEMALE", "Admitted: women"],
  ["ADM_FY_ADMITTED_ANOTHER", "Admitted: another gender"],
  ["ADM_FY_ADMITTED_UNKNOWN", "Admitted: gender unknown"],
  ["ADM_FY_ADMITTED_INSTATE", "Admitted: in-state"],
  ["ADM_FY_ADMITTED_OUTSTATE", "Admitted: out-of-state"],
  ["ADM_FY_ADMITTED_INTL", "Admitted: international"],
  ["ADM_FY_ADMITTED_RESIDENCY_UNKNOWN", "Admitted: residency unknown"],
  ["ADM_FY_ADMITTED_RESIDENCY_TOTAL", "Admitted: residency total"],
  ["ADM_FY_ENROLLED_TOTAL", "Enrolled: total"],
  ["ADM_FY_ENROLLED_MALE", "Enrolled: men"],
  ["ADM_FY_ENROLLED_FEMALE", "Enrolled: women"],
  ["ADM_FY_ENROLLED_ANOTHER", "Enrolled: another gender"],
  ["ADM_FY_ENROLLED_UNKNOWN", "Enrolled: gender unknown"],
  ["ADM_FY_ENROLLED_INSTATE", "Enrolled: in-state"],
  ["ADM_FY_ENROLLED_OUTSTATE", "Enrolled: out-of-state"],
  ["ADM_FY_ENROLLED_INTL", "Enrolled: international"],
  ["ADM_FY_ENROLLED_RESIDENCY_UNKNOWN", "Enrolled: residency unknown"],
  ["ADM_FY_ENROLLED_RESIDENCY_TOTAL", "Enrolled: residency total"],
  /* C12 */
  ["ADM_AVG_HS_GPA", "Average high school GPA (enrolled first-years)"],
  ["ADM_PCT_SUBMITTED_GPA", "Percent submitting high school GPA"],
  /* D2 */
  ["TRAN_APPLIED_TOTAL", "Transfer applied: total"],
  ["TRAN_APPLIED_MALE", "Transfer applied: men"],
  ["TRAN_APPLIED_FEMALE", "Transfer applied: women"],
  ["TRAN_APPLIED_UNKNOWN", "Transfer applied: gender unknown"],
  ["TRAN_ADMITTED_TOTAL", "Transfer admitted: total"],
  ["TRAN_ADMITTED_MALE", "Transfer admitted: men"],
  ["TRAN_ADMITTED_FEMALE", "Transfer admitted: women"],
  ["TRAN_ADMITTED_UNKNOWN", "Transfer admitted: gender unknown"],
  ["TRAN_ENROLLED_TOTAL", "Transfer enrolled: total"],
  ["TRAN_ENROLLED_MALE", "Transfer enrolled: men"],
  ["TRAN_ENROLLED_FEMALE", "Transfer enrolled: women"],
  ["TRAN_ENROLLED_UNKNOWN", "Transfer enrolled: gender unknown"],
  /* F1 */
  ["HOUSING_PCT_ON_CAMPUS_FTFY", "Living in college housing (first-time first-year)"],
  ["HOUSING_PCT_OFF_CAMPUS_FTFY", "Living off campus or commuting (first-time first-year)"],
  ["HOUSING_PCT_ON_CAMPUS_UG", "Living in college housing (all undergrads)"],
  ["HOUSING_PCT_OFF_CAMPUS_UG", "Living off campus or commuting (all undergrads)"],
  ["RES_PCT_IN_STATE_FTFY", "In-state residents (first-time first-year)"],
  ["RES_PCT_OUT_OF_STATE_FTFY", "Out-of-state residents (first-time first-year)"],
  ["RES_PCT_IN_STATE_UG", "In-state residents (all undergrads)"],
  ["RES_PCT_OUT_OF_STATE_UG", "Out-of-state residents (all undergrads)"],
  ["GREEK_PCT_MALE_FRAT_FTFY", "Men in fraternities (first-time first-year)"],
  ["GREEK_PCT_FEMALE_SOR_FTFY", "Women in sororities (first-time first-year)"],
  ["GREEK_PCT_MALE_FRAT_UG", "Men in fraternities (all undergrads)"],
  ["GREEK_PCT_FEMALE_SOR_UG", "Women in sororities (all undergrads)"],
  ["AGE_AVG_ALL_FTFY", "Average age, all students (first-time first-year)"],
  ["AGE_AVG_FT_FTFY", "Average age, full-time students (first-time first-year)"],
  ["AGE_PCT_25_PLUS_FTFY", "Age 25 or older (first-time first-year)"],
  ["AGE_AVG_ALL_UG", "Average age, all students (all undergrads)"],
  ["AGE_AVG_FT_UG", "Average age, full-time students (all undergrads)"],
  ["AGE_PCT_25_PLUS_UG", "Age 25 or older (all undergrads)"],
  ["F1_SECOND_COLUMN_LABEL", "F1 table basis (second column heading)"],
  /* G1 */
  ["TUIT_COST_YEAR", "Cost figures apply to academic year"],
  ["TUIT_INSTATE_FY_USD", "Tuition, in-state (first-year)"],
  ["TUIT_OUTSTATE_FY_USD", "Tuition, out-of-state (first-year)"],
  ["FEES_REQUIRED_FY_USD", "Required fees (first-year)"],
  ["ROOM_BOARD_FY_USD", "Room and board, on campus (first-year)"],
  ["TUIT_INSTATE_UG_USD", "Tuition, in-state (undergraduate)"],
  ["TUIT_OUTSTATE_UG_USD", "Tuition, out-of-state (undergraduate)"],
  ["FEES_REQUIRED_UG_USD", "Required fees (undergraduate)"],
  ["ROOM_BOARD_UG_USD", "Room and board, on campus (undergraduate)"],
  /* H2 */
  ["AID_UG_DEGREE_SEEKING_FTFY_N", "Degree-seeking students: first-time full-time"],
  ["AID_UG_DEGREE_SEEKING_FT_UG_N", "Degree-seeking students: full-time undergrads"],
  ["AID_UG_DEGREE_SEEKING_LT_FT_N", "Degree-seeking students: less than full-time"],
  ["AID_UG_APPLIED_NEED_FTFY_N", "Applied for need-based aid: first-time full-time"],
  ["AID_UG_APPLIED_NEED_FT_UG_N", "Applied for need-based aid: full-time undergrads"],
  ["AID_UG_APPLIED_NEED_LT_FT_N", "Applied for need-based aid: less than full-time"],
  ["AID_UG_WITH_NEED_FTFY_N", "Determined to have financial need: first-time full-time"],
  ["AID_UG_WITH_NEED_FT_UG_N", "Determined to have financial need: full-time undergrads"],
  ["AID_UG_WITH_NEED_LT_FT_N", "Determined to have financial need: less than full-time"],
  ["AID_UG_AWARDED_ANY_FTFY_N", "Awarded any need-based aid: first-time full-time"],
  ["AID_UG_AWARDED_ANY_FT_UG_N", "Awarded any need-based aid: full-time undergrads"],
  ["AID_UG_AWARDED_ANY_LT_FT_N", "Awarded any need-based aid: less than full-time"],
  ["AID_UG_NEED_GRANT_FTFY_N", "Awarded need-based scholarship or grant: first-time full-time"],
  ["AID_UG_NEED_GRANT_FT_UG_N", "Awarded need-based scholarship or grant: full-time undergrads"],
  ["AID_UG_NEED_GRANT_LT_FT_N", "Awarded need-based scholarship or grant: less than full-time"],
  ["AID_UG_NEED_FULLY_MET_FTFY_N", "Need fully met: first-time full-time"],
  ["AID_UG_NEED_FULLY_MET_FT_UG_N", "Need fully met: full-time undergrads"],
  ["AID_UG_NEED_FULLY_MET_LT_FT_N", "Need fully met: less than full-time"],
  ["AID_UG_PCT_NEED_MET_FTFY", "Average percent of need met: first-time full-time"],
  ["AID_UG_PCT_NEED_MET_FT_UG", "Average percent of need met: full-time undergrads"],
  ["AID_UG_PCT_NEED_MET_LT_FT", "Average percent of need met: less than full-time"],
  ["AID_UG_AVG_NEED_PKG_FTFY_USD", "Average need-based aid package: first-time full-time"],
  ["AID_UG_AVG_NEED_PKG_FT_UG_USD", "Average need-based aid package: full-time undergrads"],
  ["AID_UG_AVG_NEED_PKG_LT_FT_USD", "Average need-based aid package: less than full-time"],
  /* H5 */
  ["DEBT_PCT_BORROWING", "Graduates who borrowed"],
  ["DEBT_N_BORROWING", "Number of graduates who borrowed"],
  ["DEBT_AVG_CUMULATIVE_USD", "Average cumulative debt per borrower"],
  /* J1 */
  ["DEG_CIP_AGRICULTURE_PCT", "Agriculture"],
  ["DEG_CIP_ARCHITECTURE_PCT", "Architecture"],
  ["DEG_CIP_AREA_ETHNIC_AND_GENDER_STUDIES_PCT", "Area, ethnic and gender studies"],
  ["DEG_CIP_BIOLOGICAL_LIFE_SCIENCES_PCT", "Biological / life sciences"],
  ["DEG_CIP_BUSINESS_MARKETING_PCT", "Business / marketing"],
  ["DEG_CIP_COMMUNICATION_JOURNALISM_PCT", "Communication / journalism"],
  ["DEG_CIP_COMMUNICATION_TECHNOLOGIES_PCT", "Communication technologies"],
  ["DEG_CIP_COMPUTER_AND_INFORMATION_SCIENCES_PCT", "Computer and information sciences"],
  ["DEG_CIP_CONSTRUCTION_TRADES_PCT", "Construction trades"],
  ["DEG_CIP_EDUCATION_PCT", "Education"],
  ["DEG_CIP_ENGINEERING_PCT", "Engineering"],
  ["DEG_CIP_ENGINEERING_TECHNOLOGIES_PCT", "Engineering technologies"],
  ["DEG_CIP_ENGLISH_PCT", "English"],
  ["DEG_CIP_FAMILY_AND_CONSUMER_SCIENCES_PCT", "Family and consumer sciences"],
  ["DEG_CIP_FOREIGN_LANGUAGES_LITERATURES_AND_LINGUISTICS_PCT", "Foreign languages, literatures and linguistics"],
  ["DEG_CIP_HEALTH_PROFESSIONS_AND_RELATED_PROGRAMS_PCT", "Health professions and related programs"],
  ["DEG_CIP_HISTORY_PCT", "History"],
  ["DEG_CIP_INTERDISCIPLINARY_STUDIES_PCT", "Interdisciplinary studies"],
  ["DEG_CIP_LAW_LEGAL_STUDIES_PCT", "Law / legal studies"],
  ["DEG_CIP_LIBERAL_ARTS_GENERAL_STUDIES_PCT", "Liberal arts / general studies"],
  ["DEG_CIP_LIBRARY_SCIENCE_PCT", "Library science"],
  ["DEG_CIP_MATHEMATICS_AND_STATISTICS_PCT", "Mathematics and statistics"],
  ["DEG_CIP_MECHANIC_AND_REPAIR_TECHNOLOGIES_PCT", "Mechanic and repair technologies"],
  ["DEG_CIP_MILITARY_SCIENCE_AND_MILITARY_TECHNOLOGIES_PCT", "Military science and technologies"],
  ["DEG_CIP_NATURAL_RESOURCES_AND_CONSERVATION_PCT", "Natural resources and conservation"],
  ["DEG_CIP_PARKS_AND_RECREATION_PCT", "Parks and recreation"],
  ["DEG_CIP_PERSONAL_AND_CULINARY_SERVICES_PCT", "Personal and culinary services"],
  ["DEG_CIP_PHILOSOPHY_AND_RELIGIOUS_STUDIES_PCT", "Philosophy and religious studies"],
  ["DEG_CIP_PHYSICAL_SCIENCES_PCT", "Physical sciences"],
  ["DEG_CIP_PRECISION_PRODUCTION_PCT", "Precision production"],
  ["DEG_CIP_PSYCHOLOGY_PCT", "Psychology"],
  ["DEG_CIP_PUBLIC_ADMINISTRATION_AND_SOCIAL_SERVICES_PCT", "Public administration and social services"],
  ["DEG_CIP_SCIENCE_TECHNOLOGIES_PCT", "Science technologies"],
  ["DEG_CIP_SOCIAL_SCIENCES_PCT", "Social sciences"],
  ["DEG_CIP_THEOLOGY_AND_RELIGIOUS_VOCATIONS_PCT", "Theology and religious vocations"],
  ["DEG_CIP_TRANSPORTATION_AND_MATERIALS_MOVING_PCT", "Transportation and materials moving"],
  ["DEG_CIP_VISUAL_AND_PERFORMING_ARTS_PCT", "Visual and performing arts"],
];
